"""total_cost column added in vehicle table

Revision ID: 1adc39908442
Revises: 7de8161d9d00
Create Date: 2025-10-03 14:51:47.899244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1adc39908442'
down_revision: Union[str, Sequence[str], None] = '7de8161d9d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('total_cost', sa.Float(), nullable=True, comment='Total cost of the vehicle'))
    op.alter_column('vehicles', 'base_price',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Float(),
               existing_comment='Base price of the vehicle',
               existing_nullable=True)
    op.alter_column('vehicles', 'sales_tax',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Float(),
               existing_comment='Sales tax applied to the vehicle',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'sales_tax',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=255),
               existing_comment='Sales tax applied to the vehicle',
               existing_nullable=True)
    op.alter_column('vehicles', 'base_price',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=255),
               existing_comment='Base price of the vehicle',
               existing_nullable=True)
    op.drop_column('vehicles', 'total_cost')
    # ### end Alembic commands ###
