"""trip number included

Revision ID: 2f1913b555de
Revises: d294b1f9a30b
Create Date: 2025-09-22 22:22:59.740717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1913b555de'
down_revision: Union[str, Sequence[str], None] = 'd294b1f9a30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curb_trips', sa.Column('trip_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curb_trips', 'trip_number')
    # ### end Alembic commands ###
