"""Change lease_limit to VARCHAR(64)

Revision ID: 7de8161d9d00
Revises: 522ce2335e76
Create Date: 2025-09-30 10:53:31.235793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7de8161d9d00'
down_revision: Union[str, Sequence[str], None] = '522ce2335e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lease_configuration', 'lease_limit',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lease_configuration', 'lease_limit',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
