"""Added vehicle hack up cost and lifetime cap

Revision ID: 91f2de40b151
Revises: b4d2de4c272a
Create Date: 2025-10-08 09:19:26.788903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f2de40b151'
down_revision: Union[str, Sequence[str], None] = 'b4d2de4c272a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_hack_up_cost', sa.Integer(), nullable=True, comment='Total hack up cost of the vehicle'))
    op.add_column('vehicles', sa.Column('vehicle_lifetime_cap', sa.Integer(), nullable=True, comment='Cap calculated off between true cost or tlc cap'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'vehicle_lifetime_cap')
    op.drop_column('vehicles', 'vehicle_hack_up_cost')
    # ### end Alembic commands ###
