"""delete total cost column in vehicle tables

Revision ID: afbc8a8eed88
Revises: c3fbac3c90c2
Create Date: 2025-10-09 09:32:48.825742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'afbc8a8eed88'
down_revision: Union[str, Sequence[str], None] = 'c3fbac3c90c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corporation_payees', 'corporation_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='Foreign Key to Corporation table',
               existing_comment='Payee ID: Foreign Key to Corporation table based on the Payee Type')
    op.create_foreign_key(None, 'corporation_payees', 'corporation', ['corporation_owner_id'], ['id'])
    op.drop_column('vehicles', 'total_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('total_cost', mysql.FLOAT(), nullable=True, comment='Total cost of the vehicle'))
    op.drop_constraint(None, 'corporation_payees', type_='foreignkey')
    op.alter_column('corporation_payees', 'corporation_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='Payee ID: Foreign Key to Corporation table based on the Payee Type',
               existing_comment='Foreign Key to Corporation table')
    # ### end Alembic commands ###
