"""Added vehicle total price and vehicle true cost

Revision ID: b4d2de4c272a
Revises: dd63da6e1542
Create Date: 2025-10-07 12:04:59.763388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d2de4c272a'
down_revision: Union[str, Sequence[str], None] = 'dd63da6e1542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_total_price', sa.Integer(), nullable=True, comment='Total cost of the vehicle'))
    op.add_column('vehicles', sa.Column('vehicle_true_cost', sa.Integer(), nullable=True, comment='True cost typically could mean that hack up costs and other miscellaneous costs are accounted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'vehicle_true_cost')
    op.drop_column('vehicles', 'vehicle_total_price')
    # ### end Alembic commands ###
