"""Corpoation Payee Table added

Revision ID: c4a1008b1194
Revises: ff73cde3d243
Create Date: 2025-09-22 23:11:27.255127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4a1008b1194'
down_revision: Union[str, Sequence[str], None] = 'ff73cde3d243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporation_payees',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary Key for Corporation Payee'),
    sa.Column('corporation_id', sa.Integer(), nullable=False, comment='Foreign Key to Corporation table'),
    sa.Column('pay_to_mode', sa.String(length=25), nullable=True, comment='Pay to Mode: Check and ACH'),
    sa.Column('payee', sa.String(length=255), nullable=True, comment='Payee for the Corporation'),
    sa.Column('bank_account_id', sa.Integer(), nullable=True, comment='Foreign Key to id in the Bank Account table'),
    sa.Column('sequence', sa.Integer(), nullable=True, comment='Sequence of the Payee'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporation.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('corporation_ibfk_1'), 'corporation', type_='foreignkey')
    op.drop_constraint(op.f('corporation_ibfk_2'), 'corporation', type_='foreignkey')
    op.drop_column('corporation', 'payee')
    op.drop_column('corporation', 'additional_pay_to_mode')
    op.drop_column('corporation', 'pay_to_mode')
    op.drop_column('corporation', 'additional_bank_account_id')
    op.drop_column('corporation', 'additional_payee')
    op.drop_column('corporation', 'bank_account_id')
    op.add_column('corporation', sa.Column("is_mailing_address_same", sa.Boolean(), nullable=True, comment="Indicates whether the mailing address is the same as the primary address"))
    op.add_column('medallion_storage' , sa.Column('print_name' , sa.String(255) , nullable=True , comment = "Persion Who Approve Storage"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporation', sa.Column('bank_account_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Foreign Key to id in the Bank Account table'))
    op.add_column('corporation', sa.Column('additional_payee', mysql.VARCHAR(length=255), nullable=True, comment='Additional Payee for the Corporation'))
    op.add_column('corporation', sa.Column('additional_bank_account_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Foreign Key to id in the Bank Account table'))
    op.add_column('corporation', sa.Column('pay_to_mode', mysql.VARCHAR(length=25), nullable=True, comment='Pay to Mode: Check and ACH'))
    op.add_column('corporation', sa.Column('additional_pay_to_mode', mysql.VARCHAR(length=25), nullable=True, comment='Pay to Mode: Check and ACH'))
    op.add_column('corporation', sa.Column('payee', mysql.VARCHAR(length=255), nullable=True, comment='Payee for the Corporation'))
    op.create_foreign_key(op.f('corporation_ibfk_2'), 'corporation', 'bank_account', ['bank_account_id'], ['id'])
    op.create_foreign_key(op.f('corporation_ibfk_1'), 'corporation', 'bank_account', ['additional_bank_account_id'], ['id'])
    op.drop_table('corporation_payees')
    op.drop_column('corporation', "is_mailing_address_same")
    op.drop_column('medallion_storage' , 'print_name')
    # ### end Alembic commands ###
