"""Added additional balance due

Revision ID: c82ba83f5667
Revises: 91f2de40b151
Create Date: 2025-10-08 10:21:20.756903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82ba83f5667'
down_revision: Union[str, Sequence[str], None] = '91f2de40b151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('additional_balance_due', sa.Integer(), nullable=True, comment='Additional Balance Due'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leases', 'additional_balance_due')
    # ### end Alembic commands ###
