"""condition change in model

Revision ID: d294b1f9a30b
Revises: ff73cde3d243
Create Date: 2025-09-22 18:13:40.892312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd294b1f9a30b'
down_revision: Union[str, Sequence[str], None] = 'ff73cde3d243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curb_trips', 'period',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curb_trips', 'period',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###
