"""Added segment information

Revision ID: dd63da6e1542
Revises: 7de8161d9d00
Create Date: 2025-10-06 12:32:40.268474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd63da6e1542'
down_revision: Union[str, Sequence[str], None] = '7de8161d9d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('total_segments', sa.Integer(), nullable=True, comment='Total segments in the lease'))
    op.add_column('leases', sa.Column('current_segment', sa.Integer(), nullable=True, comment='Current segment of the lease'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leases', 'current_segment')
    op.drop_column('leases', 'total_segments')
    # ### end Alembic commands ###
