"""add Pay_to_mode column in Individual and corporation table

Revision ID: ff73cde3d243
Revises: 4bc24065adad
Create Date: 2025-09-17 11:19:03.510832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff73cde3d243'
down_revision: Union[str, Sequence[str], None] = '4bc24065adad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporation', sa.Column('pay_to_mode', sa.String(length=25), nullable=True, comment='Pay to Mode: Check and ACH'))
    op.add_column('corporation', sa.Column('additional_pay_to_mode', sa.String(length=25), nullable=True, comment='Pay to Mode: Check and ACH'))
    op.add_column('individual', sa.Column('pay_to_mode', sa.String(length=25), nullable=True, comment='Pay to Mode: Check and ACH'))
    op.add_column('medallion_owners', sa.Column('update_address_sign_mode', sa.CHAR(length=1), nullable=True, comment='Update Address Signed Mode: In Person (I) or by Mail (M) or Print (P)'))
    op.add_column('medallion_storage', sa.Column('contract_signed_mode', sa.CHAR(length=1), nullable=True, comment='Contract signed mode: Print (P) or Mail (M) or In Person (I)'))
    op.add_column('medallion_owners', sa.Column('is_mailing_address_same', sa.Boolean(), nullable=True, default=True, comment='Indicator if the mailing address is same as primary address'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('individual', 'pay_to_mode')
    op.drop_column('corporation', 'additional_pay_to_mode')
    op.drop_column('corporation', 'pay_to_mode')
    op.drop_column('medallion_storage', 'contract_signed_mode')
    op.drop_column('medallion_owners', 'update_address_sign_mode')
    op.drop_column('medallion_owners', 'is_mailing_address_same')
    # ### end Alembic commands ###
